GET http://localhost:5003

###


GET http://localhost:5003/userRouter/2


###

POST http://localhost:5003/userRouter
Content-Type: application/json

{
      "userId": 3,
      "title": "FOO",
      "body": "null"
}

###

PUT http://localhost:5003/userRouter
Content-Type: application/json

{
"userId": 1,
"id": 1,
"title": "updated title"
}

###

DELETE  http://localhost:5003/userRouter/1
